language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: cYsayh3/6eDL1yoP2NEFlYnZiSQ7FXcOlVxZgCb/ikSqNrpYoQVvr+t65VSzl7yvFbHcDPiO8cXEf6fDaqmWnoRjIqLyaQYOmfSVLmaoAPyF92ojMww1Mj7a55fjDDEHXhFGcJCBg3zHw4tAbRA4JjWNKANQvSblyzxVTnAjwrNTgz3XUC4liCbtrAPi7bcii60wV8bjVlkQq0B0M1D6W7ARhuSZk9SRQDMTt1qL+WGDhJt9MAyKxwSiTsgsKaHGm5rhZciWNTEMfzsFS0VTy/ip+KJRELEFZnxMjveRHplCdAGE8QqjGuSxjUCWVzBTQ8FHqL1LlUX835P2/PJcxqab2bfkMa9y+/aK0QdOcMmROhvB19S1I2Src/ZwUa/Un/FlRuxAFxinVfyNg49YtN1a/XAbydD0NtWxMFWxXfjAF6W3AtAhK7ZihYLyvrR2o5Mfybj2G1EBCA4z0gwb3ngbw3n3o2FUuiL0Nv5OgBQ39ZdrYCb8WzuOKeX74kcEymCr30AHqQVM1z7Mlz2Igm4daA9BZ4hFZKOee+GSCDrBEotpYivFuhdFDsoEKktLZ3QjhQ1KqZTs7O5T+dRUZQu8fEhKLRjEuO3xKh1Pi/aFTyBwg8wijbC5uIj0ZuavQi/a6ChX2ieh/1ynWTKUslp8rkLgwXZSX512wVoOEvQ=
script: mvn clean verify --settings travis-settings.xml -Dgpg.passphrase=upwork
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B -Dgpg.passphrase=upwork
