language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: cYsayh3/6eDL1yoP2NEFlYnZiSQ7FXcOlVxZgCb/ikSqNrpYoQVvr+t65VSzl7yvFbHcDPiO8cXEf6fDaqmWnoRjIqLyaQYOmfSVLmaoAPyF92ojMww1Mj7a55fjDDEHXhFGcJCBg3zHw4tAbRA4JjWNKANQvSblyzxVTnAjwrNTgz3XUC4liCbtrAPi7bcii60wV8bjVlkQq0B0M1D6W7ARhuSZk9SRQDMTt1qL+WGDhJt9MAyKxwSiTsgsKaHGm5rhZciWNTEMfzsFS0VTy/ip+KJRELEFZnxMjveRHplCdAGE8QqjGuSxjUCWVzBTQ8FHqL1LlUX835P2/PJcxqab2bfkMa9y+/aK0QdOcMmROhvB19S1I2Src/ZwUa/Un/FlRuxAFxinVfyNg49YtN1a/XAbydD0NtWxMFWxXfjAF6W3AtAhK7ZihYLyvrR2o5Mfybj2G1EBCA4z0gwb3ngbw3n3o2FUuiL0Nv5OgBQ39ZdrYCb8WzuOKeX74kcEymCr30AHqQVM1z7Mlz2Igm4daA9BZ4hFZKOee+GSCDrBEotpYivFuhdFDsoEKktLZ3QjhQ1KqZTs7O5T+dRUZQu8fEhKLRjEuO3xKh1Pi/aFTyBwg8wijbC5uIj0ZuavQi/a6ChX2ieh/1ynWTKUslp8rkLgwXZSX512wVoOEvQ=
  - secure: EsIOF+jxX5nN/rlHD6HV6MoueRJ5KYnrXICFOONm/yUDN6YJZUO7STEpWcBs9RhYz6JUqENsjxwZ5qGjsXnKCt0zvgHVNF1UXJ9yulGZOUw2uoORZ3cnxppf9GAkFalDt6NessVHOsJ3SYs6+vP4eslYTa5KQWNYBN5g6zrp1li4KS1BSmQBiowV/Z6KipP1TZep8RIN5ENcwn+6+aq5uxL9Cmdl+eXYFQ/a7JS5GQaSraTaA9VCSCj1s3bi+1aYa8sjTgZDlZIHBPdBDtftW79eO4lQj3XJ4bxqBGtvUDjYP+KrnKQu2FXAz61Df48TWhErtzx81j/iRKbZ6DoUNuFh2NWB0hFN2BFT68EmXNo4Qq1cdMLhVfYTXSfjpEuuRZ37lT6dYPNrwz+2lUO/7zqPjyAJ3+Km1mB8pf+18fHZllZ/1L7CFS/Ub92D5jyXstbec78LCvzW4yjPbEp7cIXUflX6MHMTfXLHewGnQgVAWQeTH6z/sZL4JstWbx7+G/cFVtdCkfKXkJpS6FZ6AvRnigBneXv9sf5HnII64W2CF4ZORxTSneEVOu+92msH4LXlB1Q4LV4BXzG7R7fkUxHqOU96IWmjghauMjKHFQ1KGEthrzmhIhKUaRZ+mvojOCiu1ON4p1/D08XtcASTCLfZPlPpcmuaha+1owwFw/g=
before_install:
- openssl aes-256-cbc -pass pass:$PGP_PWD -in gpg/secring.gpg.enc -out gpg/local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$PGP_PWD -in gpg/pubring.gpg.enc -out gpg/local.pubring.gpg -d
- openssl aes-256-cbc -pass pass:$PGP_PWD -in gpg/key.gpg.enc -out gpg/local.key.gpg -d

script: mvn clean verify --settings travis-settings.xml -Dgpg.passphrase=upwork
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B -Dgpg.passphrase=upwork
