language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: maNeE87trAF8QVEO9IG/hjgHo7nwwQDgj7rwWWVLR1ngT2twndsXkAPxgUcmw+A2bja3pPIxfjjFRgzs6o37STjAo6Tosw8uHnej+w13ZuLeTwpVN5SbFasVtNtTVkBqIiHyryaW71/Pri39KUrBtwR/3IAI2VF+9IiTJEhbH8d8jKt5k0ghopcEtNGl7UtioY7/V0V9arnxeJfUet9W/JAFKrbTTplrTg2axnn8z+9tX4+C2GLHbcjgmrcFbCrNURsBe7Rh8kydQ86q7udghmhlFU3RLUFhnx/FuZXp9uH2iK7UAbPxYbz/uCkYBY/vdFTSJMYhwsBeona3HByxTX14spSQPvKEDQeH/VsfRb+ZbyOeZQD/DWEjDaBP0lLFUAGEEVv1M0DrUG271+/kv5dM3sXx8Wx9GOfHdlYDThlqEAIgdy9+H16cTevmSo3cJetm4a+rCnF1wAc40WOEGx9Zez0ooIWbqmzpDxeLixwY3vjAoDR1t5X/pYv88txbn2n0oYcaD+EFdxVwTcuJnHMyYBOlm1gt5nEPVkLZ6mZ+E3uS5FL+GxaT0t0UE0OJ2MPPjYzMimYs8i+zgslx5X1o2dpm9fgIDQfat+D3t32pTTJNLa2FdW2q5NfoORv7ohiscrsbpZb6f4QSCO8zpw13w12+LSNsLOIA0HG6jZo=
script: mvn clean verify
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
